# Generated by Django 5.1.5 on 2025-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(default='DEFAULT_ASIN', max_length=20, unique=True),
        ),
    ]
