# Generated by Django 5.1.5 on 2025-01-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_asin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='asin',
        ),
    ]
