# Generated by Django 5.1.5 on 2025-02-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprofile',
            name='email',
        ),
    ]
